services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nest-application
    ports:
      - 6500:5432
 
  pgadmin:
     image: dpage/pgadmin4:latest
     environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_PORT: 80
     ports:
      - 8080:80
     volumes:
      - pgadmin:/var/lib/pgadmin
     depends_on:
      - db



volumes:
  postgres:
  pgadmin:

networks:
  app-network:
    driver: bridge